name: lint & build
on:
  push:
    branches-ignore:
      - lite
jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.7
          run_install: false

      - name: get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: install dependencies
        run: pnpm install

      - name: lint & build
        run: |
          pnpm lint
          pnpm build
